const heroes = [
  "A-Bomb",
  "Abe Sapien",
  "Abin Sur",
  "Abomination",
  "Abraxas",
  "Absorbing Man",
  "Adam Monroe",
  "Adam Strange",
  "Agent 13",
  "Agent Bob",
  "Agent Zero",
  "Air-Walker",
  "Ajax",
  "Alan Scott",
  "Alex Mercer",
  "Alex Woolsly",
  "Alfred Pennyworth",
  "Alien",
  "Allan Quatermain",
  "Amazo",
  "Ammo",
  "Ando Masahashi",
  "Angel",
  "Angel",
  "Angel Dust",
  "Angel Salvadore",
  "Angela",
  "Animal Man",
  "Annihilus",
  "Ant-Man",
  "Ant-Man II",
  "Anti-Monitor",
  "Anti-Spawn",
  "Anti-Venom",
  "Apocalypse",
  "Aquababy",
  "Aqualad",
  "Aquaman",
  "Arachne",
  "Archangel",
  "Arclight",
  "Ardina",
  "Ares",
  "Ariel",
  "Armor",
  "Arsenal",
  "Astro Boy",
  "Atlas",
  "Atlas",
  "Atom",
  "Atom",
  "Atom Girl",
  "Atom II",
  "Atom III",
  "Atom IV",
  "Aurora",
  "Azazel",
  "Azrael",
  "Aztar",
  "Bane",
  "Banshee",
  "Bantam",
  "Batgirl",
  "Batgirl",
  "Batgirl III",
  "Batgirl IV",
  "Batgirl V",
  "Batgirl VI",
  "Batman",
  "Batman",
  "Batman II",
  "Battlestar",
  "Batwoman V",
  "Beak",
  "Beast",
  "Beast Boy",
  "Beetle",
  "Ben 10",
  "Beta Ray Bill",
  "Beyonder",
  "Big Barda",
  "Big Daddy",
  "Big Man",
  "Bill Harken",
  "Billy Kincaid",
  "Binary",
  "Bionic Woman",
  "Bird-Brain",
  "Bird-Man",
  "Bird-Man II",
  "Birdman",
  "Bishop",
  "Bizarro",
  "Black Abbott",
  "Black Adam",
  "Black Bolt",
  "Black Canary",
  "Black Canary",
  "Black Cat",
  "Black Flash",
  "Black Goliath",
  "Black Knight III",
  "Black Lightning",
  "Black Mamba",
  "Black Manta",
  "Black Panther",
  "Black Widow",
  "Black Widow II",
  "Blackout",
  "Blackwing",
  "Blackwulf",
  "Blade",
  "Blaquesmith",
  "Bling!",
  "Blink",
  "Blizzard",
  "Blizzard",
  "Blizzard II",
  "Blob",
  "Bloodaxe",
  "Bloodhawk",
  "Bloodwraith",
  "Blue Beetle",
  "Blue Beetle",
  "Blue Beetle II",
  "Blue Beetle III",
  "Boba Fett",
  "Bolt",
  "Bomb Queen",
  "Boom-Boom",
  "Boomer",
  "Booster Gold",
  "Box",
  "Box III",
  "Box IV",
  "Brainiac",
  "Brainiac 5",
  "Brother Voodoo",
  "Brundlefly",
  "Buffy",
  "Bullseye",
  "Bumblebee",
  "Bumbleboy",
  "Bushido",
  "Cable",
  "Callisto",
  "Cameron Hicks",
  "Cannonball",
  "Captain America",
  "Captain Atom",
  "Captain Britain",
  "Captain Cold",
  "Captain Epic",
  "Captain Hindsight",
  "Captain Mar-vell",
  "Captain Marvel",
  "Captain Marvel",
  "Captain Marvel II",
  "Captain Midnight",
  "Captain Planet",
  "Captain Universe",
  "Carnage",
  "Cat",
  "Cat II",
  "Catwoman",
  "Cecilia Reyes",
  "Century",
  "Cerebra",
  "Chamber",
  "Chameleon",
  "Changeling",
  "Cheetah",
  "Cheetah II",
  "Cheetah III",
  "Chromos",
  "Chuck Norris",
  "Citizen Steel",
  "Claire Bennet",
  "Clea",
  "Cloak",
  "Clock King",
  "Cogliostro",
  "Colin Wagner",
  "Colossal Boy",
  "Colossus",
  "Copycat",
  "Corsair",
  "Cottonmouth",
  "Crimson Crusader",
  "Crimson Dynamo",
  "Crystal",
  "Curse",
  "Cy-Gor",
  "Cyborg",
  "Cyborg Superman",
  "Cyclops",
  "Cypher",
  "Dagger",
  "Danny Cooper",
  "Daphne Powell",
  "Daredevil",
  "Darkhawk",
  "Darkman",
  "Darkseid",
  "Darkside",
  "Darkstar",
  "Darth Maul",
  "Darth Vader",
  "Dash",
  "Data",
  "Dazzler",
  "Deadman",
  "Deadpool",
  "Deadshot",
  "Deathlok",
  "Deathstroke",
  "Demogoblin",
  "Destroyer",
  "Diamondback",
  "DL Hawkins",
  "Doc Samson",
  "Doctor Doom",
  "Doctor Doom II",
  "Doctor Fate",
  "Doctor Octopus",
  "Doctor Strange",
  "Domino",
  "Donatello",
  "Donna Troy",
  "Doomsday",
  "Doppelganger",
  "Dormammu",
  "Dr Manhattan",
  "Drax the Destroyer",
  "Ego",
  "Elastigirl",
  "Electro",
  "Elektra",
  "Elle Bishop",
  "Elongated Man",
  "Emma Frost",
  "Enchantress",
  "Energy",
  "ERG-1",
  "Ethan Hunt",
  "Etrigan",
  "Evil Deadpool",
  "Evilhawk",
  "Exodus",
  "Fabian Cortez",
  "Falcon",
  "Fallen One II",
  "Faora",
  "Feral",
  "Fighting Spirit",
  "Fin Fang Foom",
  "Firebird",
  "Firelord",
  "Firestar",
  "Firestorm",
  "Firestorm",
  "Fixer",
  "Flash",
  "Flash Gordon",
  "Flash II",
  "Flash III",
  "Flash IV",
  "Forge",
  "Franklin Richards",
  "Franklin Storm",
  "Frenzy",
  "Frigga",
  "Galactus",
  "Gambit",
  "Gamora",
  "Garbage Man",
  "Gary Bell",
  "General Zod",
  "Genesis",
  "Ghost Rider",
  "Ghost Rider II",
  "Giant-Man",
  "Giant-Man II",
  "Giganta",
  "Gladiator",
  "Goblin Queen",
  "Godzilla",
  "Gog",
  "Goku",
  "Goliath",
  "Goliath",
  "Goliath",
  "Goliath IV",
  "Gorilla Grodd",
  "Granny Goodness",
  "Gravity",
  "Greedo",
  "Green Arrow",
  "Green Goblin",
  "Green Goblin II",
  "Green Goblin III",
  "Green Goblin IV",
  "Groot",
  "Guardian",
  "Guy Gardner",
  "Hal Jordan",
  "Han Solo",
  "Hancock",
  "Harley Quinn",
  "Harry Potter",
  "Havok",
  "Hawk",
  "Hawkeye",
  "Hawkeye II",
  "Hawkgirl",
  "Hawkman",
  "Hawkwoman",
  "Hawkwoman II",
  "Hawkwoman III",
  "Heat Wave",
  "Hela",
  "Hellboy",
  "Hellcat",
  "Hellstorm",
  "Hercules",
  "Hiro Nakamura",
  "Hit-Girl",
  "Hobgoblin",
  "Hollow",
  "Hope Summers",
  "Howard the Duck",
  "Hulk",
  "Human Torch",
  "Huntress",
  "Husk",
  "Hybrid",
  "Hydro-Man",
  "Hyperion",
  "Iceman",
  "Impulse",
  "Indiana Jones",
  "Indigo",
  "Ink",
  "Invisible Woman",
  "Iron Fist",
  "Iron Man",
  "Iron Monger",
  "Isis",
  "Jack Bauer",
  "Jack of Hearts",
  "Jack-Jack",
  "James Bond",
  "James T. Kirk",
  "Jar Jar Binks",
  "Jason Bourne",
  "Jean Grey",
  "Jean-Luc Picard",
  "Jennifer Kale",
  "Jesse Quick",
  "Jessica Cruz",
  "Jessica Jones",
  "Jessica Sanders",
  "Jigsaw",
  "Jim Powell",
  "JJ Powell",
  "Johann Krauss",
  "John Constantine",
  "John Stewart",
  "John Wraith",
  "Joker",
  "Jolt",
  "Jubilee",
  "Judge Dredd",
  "Juggernaut",
  "Junkpile",
  "Justice",
  "Jyn Erso",
  "K-2SO",
  "Kang",
  "Kathryn Janeway",
  "Katniss Everdeen",
  "Kevin 11",
  "Kick-Ass",
  "Kid Flash",
  "Kid Flash II",
  "Killer Croc",
  "Killer Frost",
  "Kilowog",
  "King Kong",
  "King Shark",
  "Kingpin",
  "Klaw",
  "Kool-Aid Man",
  "Kraven II",
  "Kraven the Hunter",
  "Krypto",
  "Kyle Rayner",
  "Kylo Ren",
  "Lady Bullseye",
  "Lady Deathstrike",
  "Leader",
  "Leech",
  "Legion",
  "Leonardo",
  "Lex Luthor",
  "Light Lass",
  "Lightning Lad",
  "Lightning Lord",
  "Living Brain",
  "Living Tribunal",
  "Liz Sherman",
  "Lizard",
  "Lobo",
  "Loki",
  "Longshot",
  "Luke Cage",
  "Luke Campbell",
  "Luke Skywalker",
  "Luna",
  "Lyja",
  "Mach-IV",
  "Machine Man",
  "Magneto",
  "Magog",
  "Magus",
  "Man of Miracles",
  "Man-Bat",
  "Man-Thing",
  "Man-Wolf",
  "Mandarin",
  "Mantis",
  "Martian Manhunter",
  "Marvel Girl",
  "Master Brood",
  "Master Chief",
  "Match",
  "Matt Parkman",
  "Maverick",
  "Maxima",
  "Maya Herrera",
  "Medusa",
  "Meltdown",
  "Mephisto",
  "Mera",
  "Metallo",
  "Metamorpho",
  "Meteorite",
  "Metron",
  "Micah Sanders",
  "Michelangelo",
  "Micro Lad",
  "Mimic",
  "Minna Murray",
  "Misfit",
  "Miss Martian",
  "Mister Fantastic",
  "Mister Freeze",
  "Mister Knife",
  "Mister Mxyzptlk",
  "Mister Sinister",
  "Mister Zsasz",
  "Mockingbird",
  "MODOK",
  "Mogo",
  "Mohinder Suresh",
  "Moloch",
  "Molten Man",
  "Monarch",
  "Monica Dawson",
  "Moon Knight",
  "Moonstone",
  "Morlun",
  "Morph",
  "Moses Magnum",
  "Mr Immortal",
  "Mr Incredible",
  "Ms Marvel II",
  "Multiple Man",
  "Mysterio",
  "Mystique",
  "Namor",
  "Namor",
  "Namora",
  "Namorita",
  "Naruto Uzumaki",
  "Nathan Petrelli",
  "Nebula",
  "Negasonic Teenage Warhead",
  "Nick Fury",
  "Nightcrawler",
  "Nightwing",
  "Niki Sanders",
  "Nina Theroux",
  "Nite Owl II",
  "Northstar",
  "Nova",
  "Nova",
  "Odin",
  "Offspring",
  "Omega Red",
  "Omniscient",
  "One Punch Man",
  "One-Above-All",
  "Onslaught",
  "Oracle",
  "Osiris",
  "Overtkill",
  "Ozymandias",
  "Parademon",
  "Paul Blart",
  "Penance",
  "Penance I",
  "Penance II",
  "Penguin",
  "Phantom",
  "Phantom Girl",
  "Phoenix",
  "Plantman",
  "Plastic Lad",
  "Plastic Man",
  "Plastique",
  "Poison Ivy",
  "Polaris",
  "Power Girl",
  "Power Man",
  "Predator",
  "Professor X",
  "Professor Zoom",
  "Psylocke",
  "Punisher",
  "Purple Man",
  "Pyro",
  "Q",
  "Quantum",
  "Question",
  "Quicksilver",
  "Quill",
  `Ra's Al Ghul`,
  "Rachel Pirzad",
  "Rambo",
  "Raphael",
  "Raven",
  "Ray",
  "Razor-Fist II",
  "Red Arrow",
  "Red Hood",
  "Red Hulk",
  "Red Mist",
  "Red Robin",
  "Red Skull",
  "Red Tornado",
  "Redeemer II",
  "Redeemer III",
  "Renata Soliz",
  "Rey",
  "Rhino",
  "Rick Flag",
  "Riddler",
  "Rip Hunter",
  "Ripcord",
  "Robin",
  "Robin II",
  "Robin III",
  "Robin V",
  "Robin VI",
  "Rocket Raccoon",
  "Rogue",
  "Ronin",
  "Rorschach",
  "Sabretooth",
  "Sage",
  "Sandman",
  "Sasquatch",
  "Sauron",
  "Savage Dragon",
  "Scarecrow",
  "Scarlet Spider",
  "Scarlet Spider II",
  "Scarlet Witch",
  "Scorpia",
  "Scorpion",
  "Sebastian Shaw",
  "Sentry",
  "Shadow King",
  "Shadow Lass",
  "Shadowcat",
  "Shang-Chi",
  "Shatterstar",
  "She-Hulk",
  "She-Thing",
  "Shocker",
  "Shriek",
  "Shrinking Violet",
  "Sif",
  "Silk",
  "Silk Spectre",
  "Silk Spectre II",
  "Silver Surfer",
  "Silverclaw",
  "Simon Baz",
  "Sinestro",
  "Siren",
  "Siren II",
  "Siryn",
  "Skaar",
  "Snake-Eyes",
  "Snowbird",
  "Sobek",
  "Solomon Grundy",
  "Songbird",
  "Space Ghost",
  "Spawn",
  "Spectre",
  "Speedball",
  "Speedy",
  "Speedy",
  "Spider-Carnage",
  "Spider-Girl",
  "Spider-Gwen",
  "Spider-Man",
  "Spider-Man",
  "Spider-Man",
  "Spider-Woman",
  "Spider-Woman II",
  "Spider-Woman III",
  "Spider-Woman IV",
  "Spock",
  "Spyke",
  "Stacy X",
  "Star-Lord",
  "Stardust",
  "Starfire",
  "Steel",
  "Stargirl",
  "Steppenwolf",
  "Static",
  "Stormtrooper",
  "Stephanie Powell",
  "Superboy",
  "Storm",
  "Supergirl",
  "Sunspot",
  "Swamp Thing",
  "Superboy-Prime",
  "Sylar",
  "Superman",
  "T-1000",
  "Swarm",
  "T-850",
  "Synch",
  "Taskmaster",
  "T-800",
  "Thanos",
  "T-X",
  "The Comedian",
  "Tempest",
  "Thor",
  "The Cape",
  "Thunderbird",
  "Thing",
  "Thunderbird III",
  "Thor Girl",
  "Thundra",
  "Thunderbird II",
  "Tigra",
  "Thunderstrike",
  "Titan",
  "Tiger Shark",
  "Toxin",
  "Tinkerer",
  "Tracy Strauss",
  "Toad",
  "Trigon",
  "Toxin",
  "Triton",
  "Trickster",
  "Ultragirl",
  "Triplicate Girl",
  "Utgard-Loki",
  "Two-Face",
  "Valerie Hart",
  "Ultron",
  "Vanisher",
  "Vagabond",
  "Venom",
  "Valkyrie",
  "Venom III",
  "Vegeta",
  "Vertigo II",
  "Venom II",
  "Vindicator",
  "Venompool",
  "Violator",
  "Vibe",
  "Vision",
  "Vindicator",
  "Vixen",
  "Violet Parr",
  "Vulture",
  "Vision II",
  "War Machine",
  "Vulcan",
  "Warlock",
  "Walrus",
  "Warpath",
  "Warbird",
  "Watcher",
  "Warp",
  "White Canary",
  "Wasp",
  "Wildfire",
  "Weapon XI",
  "Wiz Kid",
  "White Queen",
  "Wolverine",
  "Winter Soldier",
  "Wonder Man",
  "Wolfsbane",
  "Wondra",
  "Wonder Girl",
  "X-23",
  "Wonder Woman",
  "Yellow Claw",
  "Wyatt Wingfoot",
  "Yellowjacket II",
  "X-Man",
  "Yoda",
  "Yellowjacket",
  "Zoom",
  "Ymir",
  "Zatanna",
];
export default heroes;
